/* RIFT DUEL 1.0 — original dependency-free mobile arena fighter. */
(()=>{'use strict';
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
const roster=[
['ЭМБЕР','Пламенный страж','#ff9e62','Пепельный заряд','Огненный снаряд поджигает противника.','fire',0],
['НИВАЛЬ','Ледяная охотница','#99e6ff','Мёрзлая звезда','Ледяной осколок замедляет движение.','ice',1],
['ВОЛЬТ','Штормовой техник','#e2e87c','Цепной разряд','Три быстрых электрических снаряда.','chain',2],
['НИКС','Теневая странница','#bd9eff','Шаг сквозь тень','Телепортация за спину и ближний удар.','blink',3],
['АТЛАС','Железный титан','#a5b7bf','Таран','Бронированный рывок с отбрасыванием.','charge',4],
['ЗЕФИР','Страж высоты','#81edcb','Восходящий ветер','Волна подбрасывает врага в воздух.','wind',5],
['ВАЙПЕР','Алхимик чащи','#b6ed83','Зелёная игла','Ядовитая стрела наносит урон со временем.','poison',6],
['КАЙРО','Хранитель времени','#ffdfa1','Обратный отсчёт','Восстанавливает 16 здоровья и замедляет ближнего врага.','heal',3],
['ОНИКС','Каменный воитель','#a798d6','Каменная клятва','Щит на 3 секунды и удар по земле вблизи.','guard',4],
['АСТРА','Звёздная колдунья','#afc3ff','Созвездие','Три самонаводящиеся звезды.','stars',1],
['ТАЛОН','Клинок рассвета','#f0a877','Хищный выпад','Сокращает дистанцию и наносит два удара.','talon',0],
['ЭХО','Призрачный двойник','#8de2df','Второе отражение','Два призрачных удара с задержкой.','echo',3],
['МАРА','Ночная алхимичка','#ed8db2','Нить жизни','Похищает здоровье при успешном попадании.','drain',1],
['СОЛЬ','Солнечный рыцарь','#ffd170','Солнечное копьё','Мгновенный луч на средней дистанции.','beam',0],
['ЛУНА','Лунная жрица','#c6c9ff','Лунная дуга','Большая медленная сфера с сильным толчком.','moon',1],
['ОРИОН','Звёздный следопыт','#81bddc','Двойной выстрел','Две стрелы на разной высоте.','arrows',5],
['РУНА','Хранительница печатей','#e0b1ff','Печать земли','Ловушка у ног врага с заметной задержкой.','trap',6],
['ФЕРРУМ','Магнитный кузнец','#daa78f','Магнитное поле','Притягивает противника и поражает вблизи.','pull',2],
['ДЮНА','Странник пустыни','#edca90','Песчаный вихрь','Круговая атака и короткая неуязвимость.','sand',5],
['КОРАЛЛ','Страж прилива','#f6a7a2','Тяжёлая волна','Отталкивает врага мощным водяным снарядом.','tide',4],
['ТЕРН','Дух древнего леса','#9aca82','Живые корни','Корни временно удерживают соперника на месте.','root',6],
['ПРИЗМА','Зеркальная вестница','#e0c3e8','Отражение','Отражает снаряды в течение трёх секунд.','reflect',1],
['ФЛЮКС','Пилот разлома','#87e9ef','Аварийный скачок','Отступает скачком и выпускает плазменный заряд.','retreat',2],
['МИАЗМА','Болотная ведьма','#bbd083','Едкая печать','Ядовитая ловушка под противником.','venom',6],
['РЕВЕН','Бестелесный воин','#9a9cc7','Бесплотность','Неуязвимость и короткий теневой удар.','phase',3],
['СЭЙРАН','Стальной дуэлянт','#f0e7d2','Стальной полумесяц','Длинный удар клинком с высоким уроном.','blade',0],
['НОВА','Звёздный разрушитель','#fc9bce','Сверхновая','Взрыв вокруг бойца после короткой подготовки.','nova',4],
['БАСТИОН','Крепостной страж','#cbb891','Несокрушимость','Щит и восстановление 10 здоровья.','fortify',4],
['СЕЙБЛ','Сумеречная лисица','#d4a2ca','Дымовая атака','Выпад из дыма и замедление при попадании.','smoke',3],
['ТОРРЕНТ','Повелитель потоков','#82badf','Каскад','Три низкие волны подряд.','cascade',5],
['СИНДЕР','Огненная кочевница','#fbb77b','Дыхание печи','Два близких огненных заряда на разных высотах.','cone',6],
['ГЕКС','Проклятый книжник','#b3a3db','Сломанная печать','Снаряд ослабляет атаки противника.','curse',6],
['ГЕЛИОС','Воин золотого круга','#ffdc88','Столп рассвета','Световой столп подбрасывает ближнего врага.','pillar',0],
['КОМЕТА','Небесная охотница','#9fdad3','Падающая звезда','Метеор падает в отмеченную точку.','meteor',5],
['МОРРОУ','Страж гравитации','#b2b0ce','Коллапс','Притяжение, удар и замедление.','gravity',2],
['ЭЙДОЛОН','Эхо забытого мира','#addbd0','Призыв из-за спины','Призрачный снаряд возникает позади врага.','summon',3],
['НУЛЬ','Ядро разлома','#e4e9f2','Нулевая точка','Импульс истощает энергию при попадании.','null',2]
].map((r,i)=>({id:i,name:r[0],title:r[1],color:r[2],skill:r[3],desc:r[4],type:r[5],body:r[6],hp:100+(i%4)*4,speed:175+(i%5)*9,power:.94+(i%4)*.035,cd:6+(i%4)*.7}));
const arenaNames=['Небесные врата','Ледяной собор','Электрический квартал','Храм затмения','Железная цитадель','Монастырь облаков','Нефритовая чаща','Пески времени','Чёрный обелиск','Звёздная обсерватория','Багровый перевал','Зеркальный предел','Сад ночных лилий','Солнечный амфитеатр','Лунные ступени','Станция «Орион»','Руины печатей','Магнитная кузня','Затерянный караван','Гавань кораллов','Древо истоков','Кристальный зал','Порт разлома','Болотный алтарь','Безмолвный некрополь','Двор стальных клинков','Край сверхновой','Крепость последнего дня','Сумеречный рынок','Затопленный дворец','Огненная кальдера','Библиотека проклятий','Золотой горизонт','Осколки орбиты','Колодец гравитации','Призрачная пристань','Сердце разлома'];
const sceneKinds=[0,1,2,0,3,4,5,6,3,7,6,1,5,0,0,7,3,8,6,9,5,1,2,5,3,0,7,8,2,9,8,3,6,7,7,9,0];
const arenas=arenaNames.map((name,id)=>({id,name,kind:sceneKinds[id],accent:roster[id].color,seed:7331+id*809}));
const mods=[{name:'КЛАССИЧЕСКИЕ ПРАВИЛА',gravity:1,speed:1,energy:1},{name:'НИЗКАЯ ГРАВИТАЦИЯ',gravity:.62,speed:1,energy:1},{name:'ПЕРЕГРУЗКА ЭНЕРГИИ',gravity:1,speed:1,energy:1.8},{name:'УСКОРЕННЫЙ РАЗЛОМ',gravity:1,speed:1.16,energy:1},{name:'ЖИВОЙ ИСТОЧНИК · РЕГЕНЕРАЦИЯ',gravity:1,speed:1,energy:1,regen:1.1},{name:'НОЧНОЙ ТУМАН',gravity:1,speed:1,energy:1,fog:true}];
let saved={};try{saved=JSON.parse(localStorage.getItem('rift-duel-v1')||'{}')||{};}catch(_){}
let settings={hero:clamp(Number(saved.hero)||0,0,36),arena:-1,mode:'quick',difficulty:1,sound:saved.sound!==false,effects:saved.effects!==false,best:Math.max(0,Number(saved.best)||0)};
function persist(){try{localStorage.setItem('rift-duel-v1',JSON.stringify({hero:settings.hero,best:settings.best,sound:settings.sound,effects:settings.effects}));}catch(_){}}
let state='home',game=null,time=0,last=0,acc=0,homeFrame=0,stageBag=[],opponentBag=[];
const input={x:0,crouch:false,held:new Set(),keys:new Set(),pointers:new Map(),stick:null,jumped:false};
function clearInput(){input.x=0;input.crouch=false;input.held.clear();input.keys.clear();input.pointers.clear();input.stick=null;input.jumped=false;$('knob').style.transform='';document.querySelectorAll('.action').forEach(b=>b.classList.remove('pressed'));}
let audio=null;
function unlockAudio(){if(!settings.sound)return;try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch(_){}}
function sfx(kind){if(!settings.sound||!audio||audio.state!=='running')return;try{const o=audio.createOscillator(),g=audio.createGain(),n=audio.currentTime;o.connect(g);g.connect(audio.destination);let f=kind==='hit'?105:kind==='block'?350:kind==='special'?510:kind==='ult'?70:kind==='win'?660:270;o.type=kind==='hit'||kind==='ult'?'sawtooth':'sine';o.frequency.setValueAtTime(f,n);o.frequency.exponentialRampToValueAtTime(kind==='win'?990:Math.max(25,f*.35),n+.16);g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(.065,n+.012);g.gain.exponentialRampToValueAtTime(.0001,n+.24);o.start(n);o.stop(n+.25);}catch(_){}}
function fighter(id,x,face){const h=roster[id];return{h,x,y:0,vx:0,vy:0,face,hp:h.hp,maxHp:h.hp,meter:0,guard:100,blocking:false,crouch:false,action:null,stun:0,inv:0,slow:0,root:0,dot:0,weak:0,shield:0,reflect:0,cd:0,dashCd:0,combo:0,comboAge:0,trail:[],ai:0,move:0,dealt:0,damageTaken:0};}
const moveDefs={light:{duration:.28,active:.10,damage:6.8,range:104,knock:85,stun:.14},heavy:{duration:.52,active:.20,damage:11,range:140,knock:175,stun:.22},special:{duration:.62,active:.23},ult:{duration:.95,active:.31,damage:29,range:340,knock:350,stun:.5}};
function doAction(f,type,g=game){if(!g||g.phase!=='fight'||f.hp<=0||f.stun>0||f.action)return false;if(type==='jump'){if(f.y<1&&!f.root){f.vy=470;f.y=1;f.blocking=false;return true;}return false;}if(type==='dash'){if(f.dashCd>0||f.root>0)return false;f.dashCd=.95;f.inv=.10;f.vx=(f===g.p&&input.x?Math.sign(input.x):f.face)*650;f.action={type:'dash',t:0,duration:.19,done:true};f.blocking=false;return true;}if(!(type in moveDefs))return false;if(type==='special'&&f.cd>0)return false;if(type==='ult'&&f.meter<99.9)return false;f.blocking=false;f.action={type,t:0,done:false,...moveDefs[type]};if(type==='special'){f.cd=f.h.cd;sfx('special');}if(type==='ult'){f.meter=0;f.inv=.42;g.flash=.12;g.shake=9;g.banner={title:f.h.name+' / РАЗЛОМ',life:1,color:f.h.color};sfx('ult');}return true;}
function effect(g,x,y,color,n=15){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,v=70+Math.random()*230;g.particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.25+Math.random()*.35,max:.6,color,r:2+Math.random()*3});}if(g.particles.length>220)g.particles.splice(0,g.particles.length-220);}
function damage(g,a,b,amount,opts={}){if(b.hp<=0||b.inv>0)return false;const front=(a.x-b.x)*b.face>=-3,blocked=b.blocking&&front&&b.y<1&&b.stun<=0;let dmg=amount*a.h.power*(a.weak>0?.65:1)*(b.shield>0?.42:1);if(blocked){dmg*=.14;b.guard-=amount*1.6;if(b.guard<=0){b.stun=.75;b.guard=22;b.blocking=false;g.labels.push({x:b.x,y:b.y+205,text:'БЛОК ПРОБИТ',life:.8,color:'#ffda91'});}sfx('block');}else{b.stun=Math.max(b.stun,opts.stun||.16);b.action=null;b.vx=(opts.knock||110)*(Math.sign(b.x-a.x)||a.face);if(opts.launch){b.vy=opts.launch;b.y=Math.max(b.y,1);}if(opts.slow)b.slow=opts.slow;if(opts.root)b.root=opts.root;if(opts.dot)b.dot=opts.dot;if(opts.weak)b.weak=opts.weak;if(opts.drain)b.meter=Math.max(0,b.meter-opts.drain);a.combo=a.comboAge<.95?a.combo+1:1;a.comboAge=0;if(a.combo>=2)g.labels.push({x:a.x,y:a.y+216,text:a.combo+' УДАРА',life:.65,color:a.h.color});sfx('hit');g.shake=Math.max(g.shake,Math.min(8,dmg*.3));}
b.hp=clamp(b.hp-dmg,0,b.maxHp);b.damageTaken+=dmg;a.dealt+=dmg;a.meter=clamp(a.meter+dmg*.9,0,100);b.meter=clamp(b.meter+dmg*.65,0,100);if(opts.leech&&!blocked)a.hp=clamp(a.hp+dmg*.75,0,a.maxHp);effect(g,b.x,b.y+105,blocked?'#cfe6ed':a.h.color,blocked?6:14);return !blocked;}
function melee(g,f,o,amount,range=140,opts={}){if(Math.abs(f.x-o.x)<range&&Math.abs(f.y-o.y)<(opts.vertical||100)&&(o.x-f.x)*f.face>-35)return damage(g,f,o,amount,opts);return false;}
function projectile(g,f,opts={}){g.projectiles.push({owner:f,x:f.x+f.face*35,y:f.y+110,vx:f.face*400,vy:0,r:12,life:2.6,damage:14,color:f.h.color,...opts});}
function delayed(g,delay,fn){g.events.push({t:delay,fn});}
function special(g,f,o){const dist=Math.abs(f.x-o.x),dir=f.face,C=f.h.color;effect(g,f.x,f.y+115,C,10);
switch(f.h.type){
case'fire':projectile(g,f,{dot:2.5,r:17});break;
case'ice':projectile(g,f,{slow:2.8,vx:dir*460,r:10});break;
case'chain':for(let i=0;i<3;i++)delayed(g,i*.14,()=>projectile(g,f,{damage:6,vx:f.face*630,r:8}));break;
case'blink':f.x=clamp(o.x-o.face*85,45,955);f.face=Math.sign(o.x-f.x)||dir;f.inv=.2;melee(g,f,o,17,115);break;
case'charge':f.shield=1;f.vx=dir*730;delayed(g,.18,()=>melee(g,f,o,21,165,{knock:330,launch:180}));break;
case'wind':projectile(g,f,{r:23,damage:12,launch:390,vx:dir*390});break;
case'poison':projectile(g,f,{damage:9,dot:5,vx:dir*540,r:9});break;
case'heal':f.hp=clamp(f.hp+16,0,f.maxHp);if(dist<230)o.slow=2;g.labels.push({x:f.x,y:f.y+200,text:'+16',life:1,color:C});break;
case'guard':f.shield=3;melee(g,f,o,12,180,{knock:180});break;
case'stars':for(let i=0;i<3;i++)delayed(g,i*.2,()=>projectile(g,f,{damage:6,home:true,y:f.y+100+i*20,vx:f.face*270,r:9}));break;
case'talon':f.x=clamp(f.x+dir*Math.min(200,Math.max(0,dist-80)),45,955);melee(g,f,o,9,125);delayed(g,.2,()=>melee(g,f,o,9,140));break;
case'echo':for(let i=0;i<2;i++)delayed(g,.18+i*.32,()=>{effect(g,o.x,o.y+115,C,12);if(Math.abs(f.x-o.x)<350)damage(g,f,o,9,{knock:70});});break;
case'drain':projectile(g,f,{damage:16,leech:true,vx:dir*380,r:15});break;
case'beam':g.beams.push({x:f.x,y:f.y+115,dir,len:440,life:.23,color:C});melee(g,f,o,20,440);break;
case'moon':projectile(g,f,{damage:22,vx:dir*225,r:26,knock:290});break;
case'arrows':projectile(g,f,{damage:9,vx:dir*650,r:7,y:f.y+70});projectile(g,f,{damage:9,vx:dir*650,r:7,y:f.y+137});break;
case'trap':g.traps.push({owner:f,x:o.x,delay:.65,life:1.5,r:70,damage:21,color:C});break;
case'pull':o.vx=(Math.sign(f.x-o.x)||1)*520;if(dist<360){o.stun=.20;delayed(g,.22,()=>melee(g,f,o,18,190));}break;
case'sand':f.inv=.6;if(dist<210&&Math.abs(f.y-o.y)<140)damage(g,f,o,17,{knock:240});g.rings.push({x:f.x,y:90,r:0,max:200,life:.6,color:C});break;
case'tide':projectile(g,f,{damage:18,knock:420,r:28,y:75,vx:dir*365});break;
case'root':projectile(g,f,{damage:10,root:1.6,y:35,r:24,vx:dir*450});break;
case'reflect':f.reflect=3;f.shield=1.5;break;
case'retreat':f.x=clamp(f.x-dir*170,45,955);f.inv=.25;projectile(g,f,{damage:16,vx:dir*480,r:13});break;
case'venom':g.traps.push({owner:f,x:o.x,delay:.5,life:2.2,r:85,damage:9,dot:4.5,color:C});break;
case'phase':f.inv=1.15;melee(g,f,o,14,200);break;
case'blade':melee(g,f,o,25,220,{knock:220});g.beams.push({x:f.x,y:f.y+120,dir,len:210,life:.22,color:C});break;
case'nova':delayed(g,.28,()=>{g.rings.push({x:f.x,y:f.y+90,r:0,max:260,life:.6,color:C});if(Math.abs(f.x-o.x)<260&&Math.abs(f.y-o.y)<160)damage(g,f,o,26,{knock:330,launch:200});});break;
case'fortify':f.shield=4;f.hp=clamp(f.hp+10,0,f.maxHp);g.labels.push({x:f.x,y:f.y+200,text:'+10 / ЩИТ',life:1,color:C});break;
case'smoke':f.inv=.32;f.x=clamp(f.x+dir*Math.min(210,Math.max(0,dist-80)),45,955);melee(g,f,o,17,140,{slow:2});break;
case'cascade':for(let i=0;i<3;i++)delayed(g,i*.23,()=>projectile(g,f,{damage:7,r:20,y:40,vx:f.face*360,knock:100}));break;
case'cone':projectile(g,f,{damage:11,r:26,vx:dir*300,life:.6,y:f.y+90,dot:1.5});projectile(g,f,{damage:10,r:24,vx:dir*320,life:.65,y:f.y+145});break;
case'curse':projectile(g,f,{damage:12,r:16,weak:4,vx:dir*350});break;
case'pillar':melee(g,f,o,20,165,{launch:460,vertical:240});g.rings.push({x:f.x+dir*90,y:70,r:0,max:160,life:.5,color:C});break;
case'meteor':g.traps.push({owner:f,x:o.x,delay:.9,life:1.4,r:105,damage:28,launch:260,color:C,meteor:true});break;
case'gravity':if(dist<420){o.vx=(Math.sign(f.x-o.x)||1)*430;damage(g,f,o,13,{slow:2.4,knock:-180});}break;
case'summon':projectile(g,f,{x:clamp(o.x+o.face*160,30,970),y:110,vx:-o.face*380,damage:18,r:19});break;
case'null':projectile(g,f,{r:29,damage:17,drain:32,vx:dir*420});break;
}}
function stepFighter(g,f,o,dt){['stun','inv','slow','root','weak','shield','reflect','cd','dashCd'].forEach(k=>f[k]=Math.max(0,f[k]-dt));f.comboAge+=dt;if(f.dot>0){f.dot-=dt;f.hp=Math.max(0,f.hp-dt*2.1);}f.meter=clamp(f.meter+dt*2.2*g.mod.energy,0,100);if(g.mod.regen)f.hp=clamp(f.hp+dt*g.mod.regen,0,f.maxHp);if(!f.blocking)f.guard=clamp(f.guard+dt*18,0,100);
if(f.action){const a=f.action;a.t+=dt;if(!a.done&&a.t>=a.active){a.done=true;if(a.type==='special')special(g,f,o);else if(a.type==='ult'){g.rings.push({x:f.x,y:f.y+95,r:0,max:330,life:.65,color:f.h.color});melee(g,f,o,a.damage,a.range,{knock:a.knock,stun:a.stun,launch:300,vertical:220});}else melee(g,f,o,a.damage,a.range,{knock:a.knock,stun:a.stun});}if(a.t>=a.duration)f.action=null;}
const locked=f.stun>0||f.root>0||(f.action&&f.action.type!=='dash');if(!locked&&!f.blocking){f.x+=f.move*f.h.speed*(f.slow>0?.5:1)*g.mod.speed*dt;}if(f.y>0||f.vy>0){f.y+=f.vy*dt;f.vy-=1100*g.mod.gravity*dt;if(f.y<=0){f.y=0;f.vy=0;effect(g,f.x,5,'#789cac',4);}}f.x+=f.vx*dt;f.vx*=Math.exp(-9*dt);f.x=clamp(f.x,45,955);if(!f.action)f.face=Math.sign(o.x-f.x)||f.face;if(f.blocking&&(f.stun>0||f.action||f.y>1))f.blocking=false;
}
function aiStep(g,dt){const f=g.e,o=g.p,dist=Math.abs(f.x-o.x),lvl=g.difficulty;f.ai-=dt;f.move=0;if(g.mode==='training'){f.blocking=false;return;}if(f.stun>0)return;if(f.ai<=0){f.ai=[.36,.23,.13][lvl]+Math.random()*.18;f.blocking=Math.random()<[.08,.20,.34][lvl]&&dist<190&&Boolean(o.action||Math.random()<.14);if(!f.action&&!f.blocking){const v=Math.random();if(f.meter>=100&&dist<310&&v<.38)doAction(f,'ult',g);else if(f.cd<=0&&v<[.18,.31,.44][lvl])doAction(f,'special',g);else if(dist<125)doAction(f,Math.random()<.61?'light':'heavy',g);else if(dist<175&&v<.6)doAction(f,'heavy',g);else if(g.projectiles.some(p=>p.owner===o&&Math.abs(p.x-f.x)<230)&&v<.45)doAction(f,'jump',g);else if(dist>260&&lvl>0&&v<.12)doAction(f,'dash',g);}}if(!f.action&&!f.blocking)f.move=dist>105?Math.sign(o.x-f.x):dist<62?-Math.sign(o.x-f.x)*.4:0;}
function step(g,dt,controlled=true){if(g.paused||g.phase==='finished')return;g.age+=dt;g.shake=Math.max(0,g.shake-dt*30);g.flash=Math.max(0,g.flash-dt);if(g.banner){g.banner.life-=dt;if(g.banner.life<=0)g.banner=null;}
for(const p of g.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy-=220*dt;p.life-=dt;}g.particles=g.particles.filter(p=>p.life>0);
for(const l of g.labels){l.y+=dt*30;l.life-=dt;}g.labels=g.labels.filter(l=>l.life>0);
for(const r of g.rings){r.life-=dt;r.r=lerp(r.r,r.max,dt*10);}g.rings=g.rings.filter(r=>r.life>0);for(const b of g.beams)b.life-=dt;g.beams=g.beams.filter(b=>b.life>0);
if(g.phase==='intro'){g.phaseTimer-=dt;if(g.phaseTimer<=0)g.phase='fight';return;}
if(g.phase==='roundEnd'){g.phaseTimer-=dt;if(g.phaseTimer<=0){if(g.rounds[0]>=2||g.rounds[1]>=2){g.phase='finished';if(g===game)showResult();}else resetRound(g);}return;}
g.clock-=dt;if(controlled){g.p.move=input.x;g.p.crouch=input.crouch;g.p.blocking=input.held.has('block')&&!g.p.action&&g.p.stun<=0;for(const a of ['light','heavy','special','ult'])if(input.held.has(a))doAction(g.p,a,g);}aiStep(g,dt);
const waiting=g.events;g.events=[];for(const e of waiting){e.t-=dt;if(e.t<=0)e.fn();else g.events.push(e);}
stepFighter(g,g.p,g.e,dt);stepFighter(g,g.e,g.p,dt);
if(Math.abs(g.p.x-g.e.x)<62&&Math.abs(g.p.y-g.e.y)<145){let side=g.p.x<g.e.x?-1:1;let mid=(g.p.x+g.e.x)/2;mid=clamp(mid,76,924);g.p.x=mid+side*31;g.e.x=mid-side*31;}
for(const p of g.projectiles){const o=p.owner===g.p?g.e:g.p;p.life-=dt;if(p.home){p.vx=lerp(p.vx,Math.sign(o.x-p.x)*340,dt*2);p.vy=clamp((o.y+100-p.y)*3,-200,200);}p.x+=p.vx*dt;p.y+=p.vy*dt;if(Math.abs(p.x-o.x)<32+p.r&&p.y>o.y+10-p.r&&p.y<o.y+(o.crouch?110:181)+p.r){if(o.reflect>0){p.owner=o;p.vx=-p.vx;p.x+=Math.sign(p.vx)*60;p.color=o.h.color;p.home=false;effect(g,o.x,100,o.h.color,10);}else{damage(g,p.owner,o,p.damage,p);p.life=0;}}}g.projectiles=g.projectiles.filter(p=>p.life>0&&p.x>-80&&p.x<1080);
for(const t of g.traps){t.delay-=dt;t.life-=dt;if(t.delay<=0&&!t.done){t.done=true;const o=t.owner===g.p?g.e:g.p;effect(g,t.x,50,t.color,28);g.rings.push({x:t.x,y:15,r:0,max:t.r,life:.4,color:t.color});if(Math.abs(o.x-t.x)<t.r&&o.y<(t.meteor?260:65))damage(g,t.owner,o,t.damage,t);}}g.traps=g.traps.filter(t=>t.life>0);
if(g.mode==='training'){g.clock=60;if(g.e.hp<g.e.maxHp&&g.e.stun===0&&g.p.comboAge>1.5)g.e.hp=Math.min(g.e.maxHp,g.e.hp+dt*65);if(g.e.hp<=0){g.e.hp=g.e.maxHp;g.e.dot=0;g.e.stun=0;}g.p.hp=g.p.maxHp;g.p.meter=clamp(g.p.meter+dt*24,0,100);return;}
if(g.p.hp<=0||g.e.hp<=0||g.clock<=0){const p=g.p.hp/g.p.maxHp,e=g.e.hp/g.e.maxHp;g.roundWinner=p===e?-1:p>e?0:1;if(g.roundWinner>=0)g.rounds[g.roundWinner]++;g.phase='roundEnd';g.phaseTimer=1.6;g.projectiles=[];g.events=[];g.traps=[];g.p.action=null;g.e.action=null;g.p.blocking=false;g.e.blocking=false;clearInput();}
}
function nextStage(){if(!stageBag.length){stageBag=shuffle(arenas.map(a=>a.id));if(game&&stageBag[stageBag.length-1]===game.arena.id)[stageBag[0],stageBag[stageBag.length-1]]=[stageBag[stageBag.length-1],stageBag[0]];}return stageBag.pop();}
function nextOpponent(){if(!opponentBag.length)opponentBag=shuffle(roster.map(h=>h.id).filter(id=>id!==settings.hero));return opponentBag.pop();}
function createGame(hero=0,enemy=1,arena=0,mode='quick',difficulty=1,run=0){return{p:fighter(hero,335,1),e:fighter(enemy,665,-1),arena:arenas[arena],seed:Math.floor(Math.random()*1e7),mode,difficulty,run,mod:mode==='arcade'?mods[run%mods.length]:mods[0],rounds:[0,0],clock:60,phase:'intro',phaseTimer:1.3,roundWinner:-1,paused:false,age:0,shake:0,flash:0,projectiles:[],particles:[],traps:[],events:[],labels:[],rings:[],beams:[],banner:null};}
function resetRound(g){const pMeter=g.p.meter,eMeter=g.e.meter;g.p=fighter(g.p.h.id,335,1);g.e=fighter(g.e.h.id,665,-1);g.p.meter=pMeter;g.e.meter=eMeter;g.clock=60;g.phase='intro';g.phaseTimer=1.3;g.projectiles=[];g.events=[];g.traps=[];g.beams=[];g.rings=[];clearInput();}
function poly(c,pts,fill,stroke,width=1){c.beginPath();pts.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();if(fill){c.fillStyle=fill;c.fill();}if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.stroke();}}
function line(c,x1,y1,x2,y2,color,width){c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.strokeStyle=color;c.lineWidth=width;c.lineCap='round';c.stroke();}
function ellipse(c,x,y,rx,ry,color){c.beginPath();c.ellipse(x,y,Math.max(.01,rx),Math.max(.01,ry),0,0,Math.PI*2);c.fillStyle=color;c.fill();}
function ring(c,x,y,r,color,w=2){c.beginPath();c.arc(x,y,Math.max(.01,r),0,Math.PI*2);c.strokeStyle=color;c.lineWidth=w;c.stroke();}
function grad(c,x,y,x2,y2,a,b){const g=c.createLinearGradient(x,y,x2,y2);g.addColorStop(0,a);g.addColorStop(1,b);return g;}
function limb(c,a,b,w,color,accent){const dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len;poly(c,[[a[0]+nx*w*.53,a[1]+ny*w*.53],[b[0]+nx*w*.4,b[1]+ny*w*.4],[b[0]-nx*w*.4,b[1]-ny*w*.4],[a[0]-nx*w*.53,a[1]-ny*w*.53]],(typeof color==='string'?grad(c,a[0]-w,a[1],b[0]+w,b[1],color,'#142034'):color),'#07111b',2);line(c,a[0]+nx*w*.33,a[1]+ny*w*.33,b[0]+nx*w*.27,b[1]+ny*w*.27,accent+'88',1.5);}
function drawFighter(c,f,t,scale=1){c.save();c.scale(scale*f.face,scale);const h=f.h,C=h.color,kind=h.body,heavy=kind===4,slender=kind===1||kind===3,wide=heavy?1.22:slender?.88:1;c.scale(wide,f.crouch?.74:1);const action=f.action,at=action?action.t/action.duration:0,atk=action?Math.sin(Math.min(1,at*1.5)*Math.PI):0,moving=Math.abs(f.move||0)>.15,walk=moving?Math.sin(t*12)*19:0,bob=moving?Math.abs(Math.cos(t*12))*3:Math.sin(t*2.8)*1.8;let lean=f.stun>0?-9:action&&action.type==='light'?atk*8:0;c.translate(lean,-bob);if(f.hp<=0){c.translate(0,7);c.rotate(-1.1);c.globalAlpha=.8;}if(f.inv>0)c.globalAlpha=.68+Math.sin(t*35)*.25;
// Atmospheric aura and cloth establish a distinctive silhouette, not a stick figure.
if(f.shield>0||f.reflect>0){c.save();c.globalAlpha*=.42;ring(c,0,-93,104,C,3);ring(c,0,-93,96,C+'88',1);c.restore();}
if(kind===3||kind===1||kind===6){poly(c,[[-21,-153],[-39,-125],[-51-Math.sin(t*3)*9,-10],[-13,-22],[19,-17],[35,-32],[22,-145]],grad(c,-45,-140,35,0,C+'66','#071421'),'#8fd3e333',1);line(c,-30,-123,-43,-30,C+'77',2);}
if(kind===0){line(c,-32,-149,-64,-44,'#768a91',7);line(c,-29,-153,-20,-177,'#e7cba4',7);line(c,-41,-143,-20,-152,C,4);poly(c,[[-4,-159],[-31,-163],[-76-Math.sin(t*4)*15,-143],[-51,-139],[-32,-153]],C+'b0');}
if(kind===5){c.beginPath();c.moveTo(-32,-164);c.quadraticCurveTo(-79,-100,-39,-26);c.strokeStyle=C+'bb';c.lineWidth=4;c.stroke();line(c,-32,-164,-39,-26,'#c3e2da77',1);}
if(kind===6){line(c,-43,-10,-43,-187,'#9b9586',5);ring(c,-43,-195,13,C,3);poly(c,[[-43,-214],[-36,-196],[-43,-184],[-50,-196]],C);}
const bh=[-12,-82],bk=[-27-walk,-42],bf=[-38-walk,-3];let fk=[29+walk,-45],ff=[47+walk,-3];if(action&&action.type==='heavy'){fk=[40+atk*31,-48-atk*53];ff=[47+atk*87,-3-atk*100];}if(f.y>1){fk=[24,-71];ff=[49,-44];bk[0]=-26;bk[1]=-60;bf[0]=-39;bf[1]=-30;}
limb(c,bh,bk,24,'#263a48',C);ellipse(c,bk[0],bk[1],12,11,'#15212c');limb(c,bk,bf,19,'#29384a',C);poly(c,[[bf[0]-9,bf[1]-11],[bf[0]+10,bf[1]-9],[bf[0]+23,bf[1]+1],[bf[0]+22,bf[1]+5],[bf[0]-12,bf[1]+4]],'#162536',C+'77');
const rearShoulder=[-18,-144],rearElbow=[-33,-116],rearHand=[-10,-119];if(action&&action.type==='ult'){rearElbow[0]=-58;rearElbow[1]=-152;rearHand[0]=-81;rearHand[1]=-180;}
limb(c,rearShoulder,rearElbow,21,'#304253',C);limb(c,rearElbow,rearHand,20,'#21354b',C);ellipse(c,rearHand[0],rearHand[1],10,10,'#738087');
// Articulated hips, sculpted chest, asymmetric armor and emissive seams.
poly(c,[[-18,-96],[20,-94],[25,-79],[5,-65],[-23,-75]],'#18232d',C+'77',1.5);
limb(c,[14,-81],fk,27,kind===4?'#4b5861':'#3a4957',C);ellipse(c,fk[0],fk[1],13,12,'#30414c');poly(c,[[fk[0]-10,fk[1]-8],[fk[0]+8,fk[1]-10],[fk[0]+12,fk[1]+4],[fk[0],fk[1]+11],[fk[0]-12,fk[1]+2]],C+'7a','#07111b');limb(c,fk,ff,22,'#37495a',C);poly(c,[[ff[0]-11,ff[1]-12],[ff[0]+10,ff[1]-9],[ff[0]+27,ff[1]+1],[ff[0]+26,ff[1]+5],[ff[0]-10,ff[1]+5]],grad(c,ff[0]-10,ff[1]-10,ff[0]+20,ff[1],C+'a0','#203241'),'#08131e',2);
poly(c,[[-22,-151],[-10,-161],[15,-158],[30,-141],[21,-105],[16,-91],[-16,-91],[-25,-116]],grad(c,-26,-140,30,-112,C+'9a','#243447'),'#070f19',2);
poly(c,[[-20,-147],[-2,-152],[22,-145],[20,-128],[0,-119],[-19,-130]],grad(c,-20,-149,25,-125,C+'bb','#33434e'),'#0d1926',2);poly(c,[[-17,-123],[0,-114],[19,-126],[16,-111],[0,-104],[-16,-111]],'#223b49',C+'55');poly(c,[[-15,-107],[0,-99],[15,-106],[14,-96],[-15,-94]],'#111e2c',C+'77');line(c,-18,-146,-1,-136,'#ffffff77',1.4);line(c,4,-137,22,-144,'#ffffff55',1.4);
poly(c,[[-2,-143],[4,-136],[-2,-128],[-8,-136]],C,'#ffffffbb',1);poly(c,[[-22,-98],[19,-99],[21,-91],[-22,-88]],'#998977');poly(c,[[-3,-100],[6,-99],[7,-89],[-4,-89]],C,'#0c1520',1.5);
if(kind===1||kind===6)poly(c,[[-15,-88],[16,-87],[24,-43],[3,-53],[-20,-40]],grad(c,-20,-85,24,-45,C+'88','#162132'),'#122535',1);
if(heavy){poly(c,[[-28,-159],[-15,-158],[-12,-139],[-36,-128],[-41,-144]],C+'99','#10202b',2);poly(c,[[-32,-157],[-37,-181],[-21,-160]],C+'bb');}
// Neck, individually varied helm, hood, hair or crown.
poly(c,[[-9,-170],[12,-170],[15,-157],[-10,-155]],'#304653');
ellipse(c,1,-177,19,24,grad(c,-18,-190,21,-168,C+'b0','#35404d'));
if(kind===3){poly(c,[[-25,-169],[-25,-192],[-7,-208],[14,-201],[27,-179],[20,-160],[12,-185],[-10,-189],[-16,-164]],grad(c,-25,-193,23,-169,C+'b0','#142536'),'#0a1521',2);}
else if(kind===1){poly(c,[[-18,-181],[-27,-190],[-16,-209],[7,-213],[25,-194],[24,-169],[36,-152],[20,-158],[12,-186],[-6,-195]],grad(c,-20,-207,32,-156,'#dbe8ed',C+'88'),'#101a2b',2);}
else if(kind===4){poly(c,[[-19,-184],[-34,-199],[-31,-176],[-17,-163]],C+'bb','#111b25');poly(c,[[12,-191],[28,-210],[28,-181],[18,-169]],C+'bb','#111b25');poly(c,[[-16,-197],[13,-200],[21,-185],[-20,-181]],'#758b93','#18212d',2);}
else if(kind===2){poly(c,[[-20,-167],[-23,-190],[-12,-202],[15,-202],[24,-185],[19,-164],[6,-158]],'#546a7a','#0d1621',2);poly(c,[[-12,-203],[-3,-219],[5,-202]],C);line(c,-20,-180,19,-184,C,5);}
else if(kind===5){poly(c,[[-26,-190],[19,-198],[34,-185],[-33,-181]],grad(c,-30,-193,30,-185,C+'bb','#293c4a'),'#111b25',2);line(c,-10,-182,17,-184,'#142632',8);line(c,-8,-183,14,-185,C,3);}
else if(kind===6){ring(c,1,-192,29,C+'99',2);poly(c,[[-20,-195],[-14,-219],[-4,-203],[5,-223],[11,-202],[24,-214],[20,-189]],C+'bb','#1e293a');}
else{poly(c,[[-19,-186],[-12,-202],[6,-206],[22,-192],[19,-183]],'#263b4c',C+'99',2);}
poly(c,[[-14,-173],[19,-178],[16,-163],[3,-155],[-13,-163]],grad(c,-13,-170,18,-161,C+'c0','#1d3043'),'#0c1521',1.5);line(c,-10,-168,13,-172,'#0d1d2c',2);line(c,-8,-163,10,-167,'#0d1d2c',2);line(c,-9,-181,0,-180,'#f5ffff',2.4);line(c,8,-183,16,-184,C,2.8);
let shoulder=[22,-144],elbow=[43,-119],hand=[53,-143];if(action&&action.type==='light'){elbow=[43+atk*13,-125-atk*13];hand=[53+atk*58,-143+atk*1];}if(f.blocking){elbow=[34,-137];hand=[37,-175];}if(action&&action.type==='special'){elbow=[44+atk*15,-122];hand=[59+atk*23,-145];}if(action&&action.type==='ult'){elbow=[47,-161];hand=[66,-185];}if(f.stun>0){elbow=[39,-125];hand=[35,-108];}
limb(c,shoulder,elbow,26,'#425b6c',C);ellipse(c,elbow[0],elbow[1],11,11,'#233344');limb(c,elbow,hand,24,grad(c,elbow[0],elbow[1],hand[0],hand[1],C+'aa','#2c3c4f'),C);poly(c,[[hand[0]-9,hand[1]-9],[hand[0]+8,hand[1]-12],[hand[0]+13,hand[1]],[hand[0]+5,hand[1]+9],[hand[0]-9,hand[1]+6]],'#8b9999','#1b2630',1.5);line(c,hand[0]-5,hand[1]-7,hand[0]+6,hand[1]-8,C,2);
poly(c,[[14,-155],[29,-158],[41,-144],[37,-132],[20,-135]],grad(c,14,-155,38,-133,C+'c9','#3a4d5c'),'#111c2a',2);line(c,21,-151,30,-151,'#e9f6ee99',2);
if(action&&(action.type==='special'||action.type==='ult')){c.save();c.globalAlpha*=.65;ring(c,hand[0],hand[1],20+Math.sin(t*24)*4,C,3);ellipse(c,hand[0],hand[1],8,8,'#fff8e4');c.restore();}
if(kind===1&&!action){ring(c,hand[0]+3,hand[1]-8,17,C+'99',1.5);}
c.restore();}
function drawArena(c,W,H,a,variant,t){const R=rng(a.seed+variant),A=a.accent,k=a.kind,floor=H*.75;
c.fillStyle=grad(c,0,0,0,H,'#080d1b',k===8?'#372026':k===5?'#15282c':k===6?'#302939':'#193043');c.fillRect(0,0,W,H);
const glow=c.createRadialGradient(W*.55,H*.3,5,W*.55,H*.3,W*.58);glow.addColorStop(0,A+'30');glow.addColorStop(.6,A+'09');glow.addColorStop(1,A+'00');c.fillStyle=glow;c.fillRect(0,0,W,H);
for(let i=0;i<42;i++){const x=R()*W,y=R()*floor*.74,r=R()*1.4+.25;c.globalAlpha=.35+R()*.45;ellipse(c,x,y,r,r,'#e8f8ff');}c.globalAlpha=1;
if(k!==2&&k!==8){let x=W*(.55+R()*.25),y=H*(.20+R()*.10),r=H*(k===7?.19:.09);ellipse(c,x,y,r,r,A+'33');ring(c,x,y,r+4,A+'44',1);if(k===7){c.save();c.translate(x,y);c.rotate(-.36);c.beginPath();c.ellipse(0,0,r*1.8,r*.29,0,0,Math.PI*2);c.strokeStyle=A+'65';c.lineWidth=6;c.stroke();c.restore();}else ellipse(c,x+r*.35,y-r*.2,r*.82,r*.82,'#102333');}
// Far silhouettes use deterministic scenery; every named arena has a unique seed and palette.
for(let layer=0;layer<3;layer++){const base=floor-(2-layer)*H*.09,pts=[[0,base]];for(let x=-40;x<W+80;x+=W/12)pts.push([x,base-(.06+R()*.22)*H]);pts.push([W,base]);poly(c,pts,['#101d2c','#122636','#132d3d'][layer]);}
if(k===0||k===4){for(let side=0;side<2;side++){const x=side?W*.84:W*.16,b=floor-10,s=H*.43;line(c,x-s*.2,b,x-s*.2,b-s,A+'1c',12);line(c,x+s*.2,b,x+s*.2,b-s,A+'1c',12);poly(c,[[x-s*.55,b-s*.9],[x-s*.48,b-s*1.03],[x+s*.48,b-s*1.03],[x+s*.55,b-s*.9]],'#142133',A+'88',2);poly(c,[[x-s*.68,b-s*1.1],[x-s*.4,b-s*1.08],[x,b-s*1.18],[x+s*.4,b-s*1.08],[x+s*.68,b-s*1.1],[x+s*.55,b-s],[x-s*.55,b-s]],'#142234',A+'bb',2);line(c,x,b-s*.98,x,b-s*.66,A+'77',2);ellipse(c,x,b-s*.6,8,12,A+'a0');}}
if(k===1){for(let i=0;i<10;i++){let x=R()*W,s=H*(.12+R()*.45),y=floor;poly(c,[[x-s*.14,y],[x-s*.12,y-s*.55],[x,y-s],[x+s*.2,y-s*.45],[x+s*.19,y]],grad(c,x-s*.1,y-s,x+s*.1,y,A+'75','#203446'),A+'99',1);line(c,x,y-s,x+s*.03,y,A+'66',1);}ring(c,W*.51,floor-H*.30,H*.23,A+'55',3);}
if(k===2||k===8){for(let i=0;i<16;i++){const w=W/13*(.5+R()*.6),x=i*W/14-20,ht=H*(.12+R()*.37),y=floor-ht;c.fillStyle=i%2?'#122335':'#1b2c3b';c.fillRect(x,y,w,ht);c.fillStyle=A+'70';c.fillRect(x+3,y,w-6,2);for(let row=0;row<6;row++)for(let col=0;col<3;col++)if(R()>.43){c.fillStyle=R()>.5?A+'77':'#74b2c32f';c.fillRect(x+8+col*w*.25,y+18+row*ht*.13,3,5);}}if(k===8){ellipse(c,W*.51,floor-H*.17,H*.17,H*.17,'#ffae4438');ring(c,W*.51,floor-H*.17,H*.17,A+'99',12);for(let i=0;i<3;i++)line(c,W*(.3+i*.17),floor-H*.5,W*(.3+i*.17),floor,'#132436',H*.035);}else{for(let i=0;i<3;i++){const x=W*(.12+i*.37),y=floor-H*(.22+R()*.2);c.fillStyle=A+'c0';c.fillRect(x,y,4,H*.1);c.fillStyle=A+'24';c.fillRect(x-8,y,20,H*.1);}}}
if(k===3){for(let i=0;i<7;i++){const x=i*W/6,w=W*.068,ht=H*(.28+R()*.22);poly(c,[[x-w,floor],[x-w,floor-ht],[x-w*.5,floor-ht-H*.07],[x,floor-ht],[x,floor]],'#132435',A+'38',1);if(i<6){c.beginPath();c.moveTo(x,floor-H*.17);c.quadraticCurveTo(x+W/12,floor-H*.54,x+W/6-w,floor-H*.17);c.strokeStyle='#24384a';c.lineWidth=9;c.stroke();}}}
if(k===5){for(let i=0;i<11;i++){const x=i*W/10+R()*25,ht=H*(.3+R()*.32),bw=H*(.012+R()*.012);line(c,x,floor,x-12,floor-ht,'#11222c',bw);for(let j=0;j<3;j++){const y=floor-ht*(.3+j*.22),dir=j%2?1:-1;line(c,x-5,y,x+dir*ht*.22,y-ht*.18,'#132b32',bw*.4);ellipse(c,x+dir*ht*.18,y-ht*.14,ht*.19,ht*.09,A+'15');}}for(let i=0;i<20;i++){let x=R()*W,y=floor-R()*H*.15;ellipse(c,x,y,2,2,A+'b0');}}
if(k===6){for(let i=0;i<4;i++){let x=W*(.12+i*.27),y=floor,r=H*(.2+R()*.15);poly(c,[[x-r*.7,y],[x,y-r],[x+r*.7,y]],grad(c,x-r,y-r,x+r,y,A+'3c','#243044'),A+'33');poly(c,[[x,y-r],[x+r*.7,y],[x+r*.1,y]],'#182537');}for(let i=0;i<3;i++){const y=floor-H*(.03+i*.04);c.beginPath();c.moveTo(0,y);c.bezierCurveTo(W*.3,y-H*.13,W*.7,y+H*.08,W,y-H*.04);c.lineTo(W,floor);c.lineTo(0,floor);c.fillStyle=['#2e3540','#33363e','#253343'][i];c.fill();}}
if(k===7){for(let i=0;i<8;i++){let x=R()*W,y=H*(.18+R()*.45),r=7+R()*25;poly(c,[[x-r,y],[x-r*.2,y-r],[x+r,y-r*.2],[x+r*.6,y+r],[x-r*.5,y+r*.6]],'#273143',A+'44');}c.save();c.translate(W*.5,floor-H*.22);c.scale(1,.55);ring(c,0,0,H*.31,A+'66',2);ring(c,0,0,H*.34,A+'33',1);c.restore();}
if(k===9){c.fillStyle='#123548';c.fillRect(0,floor-H*.14,W,H*.19);for(let i=0;i<24;i++){let x=R()*W,y=floor-H*.13+R()*H*.18;line(c,x,y,x+10+R()*50,y,A+'30',1);}for(let s=0;s<2;s++){const x=W*(s?.9:.09);line(c,x,floor,x,floor-H*.5,'#162534',9);line(c,x,floor-H*.47,x+(s?-1:1)*W*.16,floor-H*.23,'#526b7599',2);poly(c,[[x,floor-H*.46],[x+(s?-1:1)*W*.13,floor-H*.26],[x,floor-H*.26]],A+'22');}}
// Ground platform, depth lines and illuminated edge.
c.fillStyle=grad(c,0,floor,0,H,'#243b4a','#0a131f');c.fillRect(0,floor,W,H-floor);line(c,0,floor,W,floor,A+'b0',2);line(c,0,floor+5,W,floor+5,A+'22',3);
for(let i=-4;i<12;i++){c.beginPath();c.moveTo(W*.5+(i-3.5)*W*.1,floor);c.lineTo(W*.5+(i-3.5)*W*.26,H);c.strokeStyle='#87b1bc15';c.lineWidth=1;c.stroke();}for(let i=0;i<4;i++){const y=floor+(H-floor)*(i*i/10);line(c,0,y,W,y,'#87b1bc14',1);}
for(let i=0;i<2;i++){const x=W*(i?.95:.05);c.fillStyle='#172534';c.fillRect(x-8,floor-36,16,36);const fire=c.createRadialGradient(x,floor-40,0,x,floor-40,35);fire.addColorStop(0,A+'b0');fire.addColorStop(1,A+'00');c.fillStyle=fire;c.fillRect(x-35,floor-75,70,70);poly(c,[[x-6,floor-32],[x-9,floor-44],[x+Math.sin(t*4+i)*4,floor-64],[x+3,floor-47],[x+8,floor-40],[x+5,floor-32]],A+'cc');}
const fog=c.createLinearGradient(0,floor-H*.2,0,floor+15);fog.addColorStop(0,A+'00');fog.addColorStop(.75,A+'09');fog.addColorStop(1,A+'00');c.fillStyle=fog;c.fillRect(0,floor-H*.2,W,H*.22);
// Deterministic drifting snow, embers or motes, varied per battle without network calls.
for(let i=0;i<24;i++){let x=(R()*W+t*(k===1?7:12+i*.3))%(W+20)-10,y=(R()*H+t*(k===1?12:-7))%H;if(y<0)y+=H;c.globalAlpha=.15+R()*.30;ellipse(c,x,y,k===1?1.7:1.1,k===1?1.7:1.1,A);}c.globalAlpha=1;
}
let backgroundCache=null,cacheKey='';
function fitCanvas(c){const r=c.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,2),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(c.width!==w||c.height!==h){c.width=w;c.height=h;}return{w:r.width,h:r.height,d};}
function renderBattle(){if(!game)return;const g=game,c=$('battle'),{w:W,h:H,d}=fitCanvas(c),ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);const key=[W,H,g.arena.id,g.seed].join('-');if(cacheKey!==key){cacheKey=key;backgroundCache=document.createElement('canvas');backgroundCache.width=c.width;backgroundCache.height=c.height;const bc=backgroundCache.getContext('2d');bc.scale(d,d);drawArena(bc,W,H,g.arena,g.seed,0);}ctx.drawImage(backgroundCache,0,0,W,H);
const landscape=W>H,view=Math.max(landscape?1050:610,Math.abs(g.p.x-g.e.x)+240),sc=Math.min(W/view,H/340),mid=(g.p.x+g.e.x)/2,cam=view>=1000?500:clamp(mid,view/2,1000-view/2),floor=H*.75;ctx.save();const shake=settings.effects?g.shake:0;ctx.translate(W*.5-cam*sc+(Math.random()-.5)*shake,floor+(Math.random()-.5)*shake*.5);ctx.scale(sc,sc);
for(const f of [g.p,g.e]){ellipse(ctx,f.x,6,50-(Math.min(150,f.y)/8),8,'#020a13a8');}
for(const t of g.traps){ctx.save();ctx.globalAlpha=.5+Math.sin(time*15)*.3;ellipse(ctx,t.x,0,t.r,12,t.color+'40');ctx.beginPath();ctx.ellipse(t.x,0,t.r,12,0,0,Math.PI*2);ctx.strokeStyle=t.color;ctx.lineWidth=2;ctx.stroke();if(t.meteor){line(ctx,t.x,-280,t.x,0,t.color+'40',2);poly(ctx,[[t.x-8,-15],[t.x,-5],[t.x+8,-15]],t.color);}ctx.restore();}
for(const f of [g.e,g.p]){ctx.save();ctx.translate(f.x,-f.y);drawFighter(ctx,f,time,1);ctx.restore();if(f.dot>0){ellipse(ctx,f.x+22,-f.y-180,4,4,'#bce890');}if(f.slow>0||f.root>0){ring(ctx,f.x,-f.y-25,27,'#a4ddff88',2);}}
for(const b of g.beams){ctx.save();ctx.globalAlpha=clamp(b.life*5,0,1);line(ctx,b.x,-b.y,b.x+b.dir*b.len,-b.y,b.color+'44',22);line(ctx,b.x,-b.y,b.x+b.dir*b.len,-b.y,b.color,6);line(ctx,b.x,-b.y,b.x+b.dir*b.len,-b.y,'#fffbea',2);ctx.restore();}
for(const p of g.projectiles){ctx.save();ctx.translate(p.x,-p.y);const tail=-Math.sign(p.vx);poly(ctx,[[0,-p.r*.6],[tail*(30+p.r*2),0],[0,p.r*.6]],p.color+'70');const glow=ctx.createRadialGradient(0,0,1,0,0,p.r*2);glow.addColorStop(0,p.color+'99');glow.addColorStop(1,p.color+'00');ctx.fillStyle=glow;ctx.fillRect(-p.r*2,-p.r*2,p.r*4,p.r*4);ellipse(ctx,0,0,p.r,p.r*.78,p.color);ellipse(ctx,3,-3,p.r*.47,p.r*.4,'#fffae9');ctx.restore();}
for(const p of g.particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);line(ctx,p.x,-p.y,p.x-p.vx*.025,-p.y+p.vy*.025,p.color,p.r);}ctx.globalAlpha=1;
for(const r of g.rings){ctx.save();ctx.globalAlpha=clamp(r.life*2,0,1);ring(ctx,r.x,-r.y,r.r,r.color,4);ring(ctx,r.x,-r.y,r.r*.9,r.color+'55',1);ctx.restore();}
for(const l of g.labels){ctx.globalAlpha=clamp(l.life*2,0,1);ctx.fillStyle=l.color;ctx.font='800 20px system-ui';ctx.textAlign='center';ctx.fillText(l.text,l.x,-l.y);}ctx.restore();ctx.globalAlpha=1;
if(g.mod.fog){ctx.fillStyle='#bcd8d316';ctx.fillRect(0,H*.28,W,H*.6);}if(g.flash>0&&settings.effects){ctx.fillStyle='#d7ffff16';ctx.fillRect(0,0,W,H);}if(g.banner){ctx.save();ctx.textAlign='center';ctx.font='800 '+Math.max(13,W*.024)+'px system-ui';ctx.fillStyle=g.banner.color;ctx.fillText(g.banner.title,W/2,H*.29);ctx.restore();}
updateHUD();}
function portrait(h,w=160,hei=155){const c=document.createElement('canvas');c.width=w;c.height=hei;const ctx=c.getContext('2d');ctx.fillStyle=grad(ctx,0,0,w,hei,h.color+'38','#101a28');ctx.fillRect(0,0,w,hei);ring(ctx,w*.54,hei*.58,w*.38,h.color+'40',1);line(ctx,8,hei-3,w-8,hei-3,h.color+'aa',2);ctx.save();ctx.translate(w*.45,hei*1.55);drawFighter(ctx,fighter(h.id,0,1),h.id,hei/140);ctx.restore();return c.toDataURL();}
let lastHUD='';function updateHUD(){const g=game;if(!g)return;$('pName').innerHTML=g.p.h.name+' <small>ТЫ</small>';$('eName').textContent=g.e.h.name;$('pHealth').style.width=(g.p.hp/g.p.maxHp*100)+'%';$('eHealth').style.width=(g.e.hp/g.e.maxHp*100)+'%';$('pMeter').style.width=g.p.meter+'%';$('eMeter').style.width=g.e.meter+'%';$('pRounds').textContent=(g.rounds[0]>0?'●':'○')+' '+(g.rounds[0]>1?'●':'○');$('eRounds').textContent=(g.rounds[1]>0?'●':'○')+' '+(g.rounds[1]>1?'●':'○');$('timer').textContent=g.mode==='training'?'∞':Math.max(0,Math.ceil(g.clock));$('roundLabel').textContent=g.mode==='training'?'ТРЕНИРОВКА':'РАУНД '+(g.rounds[0]+g.rounds[1]+1);$('arenaName').textContent=g.arena.name.toUpperCase();$('modifierName').textContent=(g.mode==='arcade'?'БОЙ '+(g.run+1)+' · ':'')+g.mod.name;$('specialCD').classList.toggle('hidden',g.p.cd<=0);$('specialCD').textContent=Math.ceil(g.p.cd);$('ultCD').classList.toggle('hidden',g.p.meter>=99.9);$('ultCD').textContent=Math.floor(g.p.meter)+'%';
let toast='',sub='';if(g.phase==='intro'){toast=g.phaseTimer>.45?'РАУНД '+(g.rounds[0]+g.rounds[1]+1):'В БОЙ';sub=g.mode==='training'?'ТРЕНИРОВКА':g.p.h.name+' × '+g.e.h.name;}if(g.phase==='roundEnd'){toast=g.roundWinner<0?'НИЧЬЯ':g.roundWinner===0?'ТВОЙ РАУНД':'РАУНД СОПЕРНИКА';sub=g.roundWinner===0?'ПРОДОЛЖАЙ ДАВИТЬ':'СМЕНИ ТАКТИКУ';}const key=toast+sub;if(key!==lastHUD){lastHUD=key;$('toast').classList.toggle('hidden',!toast);$('toast').innerHTML=toast+'<small>'+sub+'</small>';}}
function showScreen(name){state=name;['home','select','game'].forEach(n=>$(n).classList.toggle('hidden',n!==name));$('modal').classList.add('hidden');clearInput();last=performance.now();acc=0;}
function startMatch(continuing=false){unlockAudio();if(!continuing){stageBag=shuffle(arenas.map(a=>a.id));opponentBag=[];}const arena=continuing?nextStage():settings.arena<0?nextStage():settings.arena;if(!continuing&&settings.arena>=0)stageBag=stageBag.filter(i=>i!==arena);const run=continuing&&game?game.run+1:0;game=createGame(settings.hero,nextOpponent(),arena,settings.mode,settings.difficulty,run);if(settings.mode==='training')game.p.meter=100;cacheKey='';showScreen('game');persist();}
function modal(title,eyebrow,body,buttons){$('modalCard').innerHTML='<div class="eyebrow">'+eyebrow+'</div><h2>'+title+'</h2>'+body;buttons.forEach(b=>{const el=document.createElement('button');el.className=b.primary?'primary':'secondary';el.textContent=b.text;el.onclick=b.fn;$('modalCard').append(el);});$('modal').classList.remove('hidden');clearInput();}
function pause(){if(state!=='game'||!game||game.phase==='finished'||game.paused)return;game.paused=true;modal('Пауза','RIFT // DUEL','<p>Бой остановлен. Продолжи, когда будешь готов.</p>',[{text:'ПРОДОЛЖИТЬ',primary:true,fn:resume},{text:'Начать матч заново',fn:()=>startMatch(false)},{text:'Выбор бойца',fn:openSelect}]);}
function resume(){if(game)game.paused=false;$('modal').classList.add('hidden');clearInput();last=performance.now();acc=0;unlockAudio();}
function showResult(){const win=game.rounds[0]>=2;if(win){settings.best=Math.max(settings.best,game.mode==='arcade'?game.run+1:1);persist();sfx('win');}const body='<p>'+game.p.h.name+' <b>'+game.rounds[0]+' : '+game.rounds[1]+'</b> '+game.e.h.name+'</p><p>'+Math.round(game.p.dealt)+' урона в последнем раунде'+(game.mode==='arcade'?'<br>Серия: '+(game.run+(win?1:0))+' · Рекорд: '+settings.best:'')+'</p>';const buttons=[];if(win&&game.mode==='arcade')buttons.push({text:'СЛЕДУЮЩИЙ РАЗЛОМ　→',primary:true,fn:()=>startMatch(true)});else buttons.push({text:'ЕЩЁ ОДИН БОЙ　→',primary:true,fn:()=>startMatch(false)});buttons.push({text:'Выбрать другого бойца',fn:openSelect});modal(win?'ПОБЕДА':'ПОРАЖЕНИЕ',win?'РАЗЛОМ ПОКОРЁН':'ЕЩЁ НЕ КОНЕЦ',body,buttons);}
function help(){modal('Твой первый бой','УПРАВЛЕНИЕ','<div class="help-grid"><p><b>Левый палец:</b> джойстик для движения; вверх — прыжок, вниз — присесть.</p><p><b>Правый палец:</b> удар рукой, ногой и уникальная сила. Удерживай кнопку для повторных атак. Сила восстанавливается несколько секунд.</p><p><b>Блок</b> нужно держать. <b>Рывок</b> сокращает дистанцию. <b>Супер</b> доступен при 100% энергии и бьёт в пределах средней дистанции.</p><p>Подойди ближе перед ударом. Матч — до двух выигранных раундов. Горизонтальный экран удобнее, вертикальный тоже поддерживается.</p><p class="muted">Клавиатура: A/D или ←/→, W/↑ — прыжок, S/↓ — присесть; J/K/L — атаки, Shift — блок, Space — рывок, U — супер, Esc — пауза.</p></div>',[{text:'ПОПРОБОВАТЬ',primary:true,fn:()=>{settings.mode='training';startMatch();}},{text:'Понятно',fn:()=>$('modal').classList.add('hidden')}]);}
function refreshSelection(){const h=roster[settings.hero];$('heroClass').textContent=h.title;$('heroName').textContent=h.name;$('heroSkill').innerHTML='<b>'+h.skill+'</b> · '+h.desc;$('heroStats').textContent='Здоровье '+h.hp+' · Скорость '+Math.round(h.speed)+' · Перезарядка '+h.cd.toFixed(1)+' с';document.querySelectorAll('.fighter-card').forEach(b=>{const active=+b.dataset.hero===h.id;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});document.querySelectorAll('.arena-card').forEach(b=>b.classList.toggle('active',+b.dataset.arena===settings.arena));document.querySelectorAll('.mode-row').forEach(b=>b.classList.toggle('active',b.dataset.mode===settings.mode));$('selectionSummary').textContent=h.name+' · '+(settings.arena<0?'Случайная арена':arenas[settings.arena].name);const c=$('heroPreview'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.save();ctx.translate(c.width*.46,c.height*.93);drawFighter(ctx,fighter(h.id,0,1),0,1.02);ctx.restore();persist();}
function openSelect(){if(game)game.paused=true;showScreen('select');refreshSelection();}
function buildSelection(){for(const h of roster){const b=document.createElement('button');b.className='fighter-card';b.dataset.hero=h.id;b.setAttribute('aria-label',h.name+': '+h.skill);const img=document.createElement('img');img.src=portrait(h);img.alt='';b.append(img);const n=document.createElement('b');n.textContent=h.name;b.append(n);const small=document.createElement('small');small.textContent=String(h.id+1).padStart(2,'0')+' / '+['КЛИНОК','МАГ','ТЕХНИК','ТЕНЬ','ТИТАН','СЛЕДОПЫТ','МИСТИК'][h.body];b.append(small);b.onclick=()=>{settings.hero=h.id;refreshSelection();sfx('ui');};$('fighters').append(b);}
const random=document.createElement('button');random.className='arena-card';random.dataset.arena=-1;random.innerHTML='<div style="height:80px;display:grid;place-items:center;font-size:35px;color:var(--cyan)">∞</div><b>Случайная арена</b>';random.onclick=()=>{settings.arena=-1;refreshSelection();};$('arenas').append(random);
for(const a of arenas){const b=document.createElement('button');b.className='arena-card';b.dataset.arena=a.id;const c=document.createElement('canvas');c.width=270;c.height=155;drawArena(c.getContext('2d'),270,155,a,0,0);const im=document.createElement('img');im.src=c.toDataURL();im.alt='';b.append(im);const n=document.createElement('b');n.textContent=String(a.id+1).padStart(2,'0')+' / '+a.name;b.append(n);b.onclick=()=>{settings.arena=a.id;refreshSelection();};$('arenas').append(b);}
refreshSelection();}
function renderHome(t){const c=$('homeArt'),{w:W,h:H,d}=fitCanvas(c),ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);drawArena(ctx,W,H,arenas[0],19,t*.25);const landscape=W>H,sc=Math.min(W/(landscape?850:455),H/(landscape?480:620)),floor=landscape?H*.89:H*.66;ctx.save();ctx.globalAlpha=.5;ring(ctx,W*.50,floor-95*sc,125*sc,'#7dfde029',1);ring(ctx,W*.50,floor-95*sc,137*sc,'#7dfde017',1);ctx.restore();for(let i=0;i<2;i++){let x=landscape?W*(i?.67:.50):W*(i?.73:.29);ctx.save();ctx.translate(x,floor);ellipse(ctx,0,4,sc*60,sc*11,'#00000088');drawFighter(ctx,fighter(i?3:0,0,i?-1:1),t+i*2,sc*(i?.96:1.02));ctx.restore();}}
const keyActions={KeyJ:'light',KeyK:'heavy',KeyL:'special',KeyU:'ult',ShiftLeft:'block',ShiftRight:'block'};
function updateMovement(){const st=input.stick;const kx=(input.keys.has('KeyD')||input.keys.has('ArrowRight')?1:0)-(input.keys.has('KeyA')||input.keys.has('ArrowLeft')?1:0);input.x=kx||(st?st.dx:0);input.crouch=input.keys.has('KeyS')||input.keys.has('ArrowDown')||Boolean(st&&st.dy>.55);input.held=new Set([...input.pointers.values(),...[...input.keys].map(k=>keyActions[k]).filter(Boolean)]);document.querySelectorAll('.action').forEach(b=>b.classList.toggle('pressed',input.held.has(b.dataset.action)));}
const stick=$('stick');function moveStick(e){if(!input.stick||input.stick.id!==e.pointerId)return;const r=stick.getBoundingClientRect(),max=r.width*.33,dx=clamp((e.clientX-r.left-r.width/2)/max,-1,1),dy=clamp((e.clientY-r.top-r.height/2)/max,-1,1);input.stick.dx=Math.abs(dx)>.18?dx:0;input.stick.dy=dy;$('knob').style.transform='translate('+dx*max+'px,'+dy*max+'px)';if(dy<-.55&&!input.jumped&&game&&!game.paused){doAction(game.p,'jump');input.jumped=true;}if(dy>-.25)input.jumped=false;updateMovement();}
stick.addEventListener('pointerdown',e=>{if(state!=='game'||!game||game.paused||input.stick)return;e.preventDefault();input.stick={id:e.pointerId,dx:0,dy:0};try{stick.setPointerCapture(e.pointerId);}catch(_){}moveStick(e);},{passive:false});stick.addEventListener('pointermove',e=>{if(input.stick&&input.stick.id===e.pointerId){e.preventDefault();moveStick(e);}},{passive:false});
function endPointer(e){if(input.stick&&input.stick.id===e.pointerId){input.stick=null;input.jumped=false;$('knob').style.transform='';}input.pointers.delete(e.pointerId);updateMovement();}
for(const name of ['pointerup','pointercancel','lostpointercapture']){stick.addEventListener(name,endPointer);window.addEventListener(name,endPointer);}
document.querySelectorAll('.action').forEach(b=>{b.addEventListener('pointerdown',e=>{if(state!=='game'||!game||game.paused)return;e.preventDefault();try{b.setPointerCapture(e.pointerId);}catch(_){}const a=b.dataset.action;input.pointers.set(e.pointerId,a);updateMovement();if(a!=='block')doAction(game.p,a);unlockAudio();},{passive:false});b.addEventListener('lostpointercapture',endPointer);});
window.addEventListener('keydown',e=>{if(e.code==='Escape'&&state==='game'){e.preventDefault();game.paused?resume():pause();return;}if(state!=='game'||!game||game.paused)return;const valid=['KeyA','KeyD','KeyW','KeyS','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space',...Object.keys(keyActions)];if(!valid.includes(e.code))return;e.preventDefault();if(!e.repeat){input.keys.add(e.code);updateMovement();if(e.code==='KeyW'||e.code==='ArrowUp')doAction(game.p,'jump');else if(e.code==='Space')doAction(game.p,'dash');else if(keyActions[e.code]&&keyActions[e.code]!=='block')doAction(game.p,keyActions[e.code]);}});
window.addEventListener('keyup',e=>{input.keys.delete(e.code);updateMovement();});window.addEventListener('blur',clearInput);document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(state==='game')pause();}last=performance.now();acc=0;});$('game').addEventListener('contextmenu',e=>e.preventDefault());$('game').addEventListener('touchmove',e=>e.preventDefault(),{passive:false});
$('chooseBtn').onclick=openSelect;$('quickBtn').onclick=()=>{settings.mode='quick';startMatch();};$('helpBtn').onclick=help;$('backHome').onclick=()=>showScreen('home');$('fightBtn').onclick=()=>startMatch();$('pauseBtn').onclick=pause;$('randomBtn').onclick=()=>{settings.hero=Math.floor(Math.random()*37);refreshSelection();};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(t=>t.classList.toggle('active',t===b));['fighters','arenas','modes'].forEach(t=>$(t).classList.toggle('hidden',t!==b.dataset.tab));});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{settings.mode=b.dataset.mode;refreshSelection();});$('difficulty').onchange=e=>settings.difficulty=+e.target.value;$('sound').value=settings.sound?'1':'0';$('sound').onchange=e=>{settings.sound=e.target.value==='1';unlockAudio();persist();};$('effects').value=settings.effects?'1':'0';$('effects').onchange=e=>{settings.effects=e.target.value==='1';persist();};
function frame(now){const dt=Math.min(.07,Math.max(0,(now-last)/1000));last=now;time+=dt;if(state==='game'&&game){if(!game.paused){acc=Math.min(acc+dt,.1);while(acc>=1/60){step(game,1/60);acc-=1/60;}}renderBattle();}else if(state==='home'&&++homeFrame%2===0)renderHome(time);requestAnimationFrame(frame);}
// Opt-in diagnostics for automated testing; not needed by gameplay.
if(new URLSearchParams(location.search).has('test'))window.__RIFT_TEST__={roster,arenas,settings,mods,createGame,step,doAction,special,damage,melee,fighter,nextStage,getGame:()=>game,getInput:()=>({x:input.x,crouch:input.crouch,held:[...input.held],pointers:input.pointers.size}),getState:()=>state,startMatch,openSelect,pause,resume,clearInput,renderBattle,drawArena,drawFighter,setStageBag:v=>stageBag=v};
try{buildSelection();renderHome(0);last=performance.now();requestAnimationFrame(frame);}catch(e){console.error(e);const box=document.createElement('div');box.className='fatal-error';box.textContent='Не удалось запустить игру. Открой страницу в актуальном Safari или Chrome. Ошибка: '+e.message;document.body.append(box);}
})();
